import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'dist');
const assets=JSON.parse(await readFile(path.join(root,'assets.json'),'utf8'));
const INSTAGRAM='https://www.instagram.com/catering_restaurant_otto/';
const MAP='https://www.google.com/maps/place/OTTO/data=!4m2!3m1!1s0x0:0xc4ad27ea14cde1a?sa=X&ved=1t:2428&ictx=111';
const languages=['ja','en'];
const names=['index','restaurant','catering','contact'];
const copy={
 ja:{
  nav:['君塚博幸のこと','レストラン','ケータリング','ご予約・店舗情報'],reserve:'ご予約・ご相談',skip:'本文へ',menu:'メニュー',close:'閉じる',lang:'言語を切り替える',location:'千葉・茂原 / 全国へケータリング',
  title:['OTTO｜料理の先に、人がいる。','レストラン｜OTTO','ケータリング｜OTTO','ご予約・店舗情報｜OTTO'],
  desc:'料理を通じて、人と人をつなぐ。オーナーシェフ君塚博幸の想いと、千葉・茂原の完全予約制レストラン、全国対応のケータリングをご紹介します。',
  hero:'料理の先に、<br>人がいる。',lead:'食べてくれる人の顔が見えること。<br>その声を、すぐそばで聞けること。<br>OTTOの料理は、いつも人とのつながりから始まります。',read:'君塚博幸の物語を読む',heroCaption:'ひと皿から、つながる時間。',
  introTitle:'料理人であり、<br>人と人をつなぐ人。',intro:'千葉・茂原のレストランから、全国のさまざまな食卓へ。OTTOのオーナーシェフ・君塚博幸が届けたいのは、料理だけではありません。人が集まり、話し、つながる時間。その中心に、料理人として立ち続けています。',chef:'オーナーシェフ',
  story:[
   {n:'01',tag:'THE BEGINNING',title:'41歳からの、<br>新しい食卓。',paragraphs:['40歳まで、会社に属する料理人として歩んできた君塚。ホテルでは料理人と総支配人を兼ね、料理をつくることと、その先にあるお客様の時間に向き合ってきました。','41歳で独立し、OTTOへ。立場が変わっても大切にしているのは、目の前にいる人のために料理をすること。これまでの経験が、レストランとケータリング、ふたつの場所でのもてなしにつながっています。'],photo:'seasonal',alt:'季節の素材を彩りよく盛り付けたOTTOのひと皿'},
   {n:'02',tag:'THE CONNECTION',title:'「8」を横にすると、<br>つながりは無限に。',paragraphs:['OTTOは、イタリア語で「8」。横にすれば、無限を表す「∞」になります。その交わるところに自分が立ち、人と人をつないでいく。店名には、そんな君塚の想いが込められています。','人とのつながりを大切にする姿勢を、君塚は「究極のお節介」と表現します。カウンターを中心としたレストランでも、出向いた先のケータリングでも。料理を囲む人たちとの近さを、大切にしています。'],photo:'gathering',alt:'たくさんの人が集う場のために並べられた彩り豊かな料理'},
   {n:'03',tag:'BEYOND THE TABLE',title:'食べることを、<br>次の世代へ。',paragraphs:['料理を届ける場所は、レストランやパーティー会場だけではありません。君塚は学校の特別講師として、食べることの大切さや、食の情報をきちんと見極めることも伝えてきました。','現在は茂原市の小・中・高校を訪れ、出張職場体験にも取り組んでいます。食をきっかけに人と関わる。その想いは、これから料理や仕事に出会う子どもたちへも広がっています。'],photo:'course',alt:'葉の上に丁寧に盛り付けられたOTTOの料理'}
  ],
  futureTitle:'どこへ出向いても、<br>お客様のそばに。',future:'ケータリングを、千葉から全国へ。活動の場を広げながらも、レストランは続けていきたいと君塚は考えています。食べてもらい、感想を聞き、次のひと皿へつなげる。そのやりとりこそが、OTTOの原点だからです。',school:'学校での授業・出張職場体験のご相談も、お電話で承ります。',
  serviceTitle:'OTTOと過ごす、<br>ふたつのかたち。',restaurantIntro:'茂原のレストランで、ひと皿ずつ。完全予約制でお迎えします。',cateringIntro:'企業のパーティーからウエディング、別荘でのコース料理まで。集う場所へ出向きます。',detail:'詳しく見る',
  restaurantHeading:'目の前のひと皿。<br>すぐそばの会話。',restaurantText:'食べてくださる方の顔を見ながら、その声を聞く。OTTOのレストランは、人と料理の距離が近い場所です。千葉・茂原で、ご予約のお客様をお迎えしています。',restaurantSub:'その日の食卓を、<br>ご一緒に。',restaurantBody:'ランチもディナーも、完全予約制。ご希望やご相談がありましたら、ご予約の際にお電話でお聞かせください。',priceFrom:'より',lunch:'ランチ',dinner:'ディナー',lastOrder:'ラストオーダー',photoNote:'写真は提供料理の一例です。内容はご予約時にご相談ください。',
  cateringHeading:'人が集う場所へ。<br>料理と、想いを。',cateringText:'料理も、場所も、過ごす時間も。企業のパーティー、ウエディング、別荘でのコース料理など、ご希望に合わせて一から組み立てるケータリングです。',cateringSub:'ひとつとして、<br>同じ食卓はない。',cateringBody:'すべてカスタマイズでお受けしています。開催場所や人数、ご予算、どんな時間にしたいか。まずはお話を聞かせてください。お客様の目の前で調理するスタイルも、ご相談いただけます。',nation:'全国対応',travel:'交通費等は別途ご相談ください。',
  occasions:[['Corporate','企業・法人のパーティー','人が集まる場に、会話が生まれる料理を。趣旨やご希望に合わせてご相談を承ります。','catering-table'],['Wedding','ウエディング','大切な人たちと囲む食卓を、おふたりの想いに合わせて。料理を通してお祝いの時間をつくります。','celebration'],['Private dining','別荘でのコース料理','くつろぎの場所で、料理人のひと皿を。ご希望の空間で楽しむコース料理をご相談ください。','villa']],
  processTitle:'ご相談から当日まで。',process:[['お電話でご相談','日時・場所・人数・ご予算など、ご希望をお聞かせください。'],['内容を一緒に組み立てる','お料理や提供スタイル、交通費等を含め、個別にご相談します。'],['集う場所へお届け','お打ち合わせした内容に合わせて、当日の食の時間をつくります。']],
  galleryTitle:'集う日の、風景。',galleryPrev:'前の写真',galleryNext:'次の写真',galleryCaptions:['会話をつなぐ、小さなひと皿。','食卓に彩りを添える料理。','集う人数に合わせたもてなし。','ひと皿ずつ仕上げるデザート。'],
  contactHeading:'食卓のこと、<br>お話ししましょう。',contactIntro:'レストランのご予約、ケータリングのご相談、学校での授業・出張職場体験について。お電話にてお気軽にお問い合わせください。',phoneLabel:'お電話でのご予約・ご相談',phone:'090-6474-6012',bookingNote:'レストランは完全予約制です。前日までにご予約ください。',ctaTitle:'次の食卓で、<br>お会いしましょう。',address:'〒297-0026<br>千葉県茂原市茂原553-5',addressLabel:'所在地',hoursLabel:'営業時間',closedLabel:'定休日',closed:'不定休（予約状況による）',bookingLabel:'ご予約',booking:'完全予約制・前日までにお電話で',map:'Googleマップで見る',instagram:'日々の料理を Instagram で',instagramText:'お料理やケータリングの様子をご紹介しています。',info:'店舗情報を見る',back:'君塚博幸の物語へ',footerTag:'料理から、人へ。人から、人へ。',notfound:'ページが見つかりません。',notfoundText:'URLをご確認いただくか、トップページからお進みください。',home:'トップページへ'
 },
 en:{
  nav:['Our chef','Restaurant','Catering','Visit & contact'],reserve:'Reservations & enquiries',skip:'Skip to content',menu:'Menu',close:'Close',lang:'Switch language',location:'MOBARA, CHIBA / CATERING ACROSS JAPAN',
  title:['OTTO | Food brings us together.','Restaurant | OTTO','Catering | OTTO','Visit & contact | OTTO'],desc:'Meet owner-chef Hiroyuki Kimiduka. Discover his philosophy, OTTO’s reservation-only restaurant in Mobara, Chiba, and bespoke catering throughout Japan.',
  hero:'Good food.<br>Real connection.',lead:'To see the people enjoying a meal.<br>To hear what they think, right there.<br>At OTTO, cooking begins with people.',read:'Meet Hiroyuki Kimiduka',heroCaption:'A plate. A moment. A connection.',introTitle:'A chef.<br>A connector of people.',intro:'From his restaurant in Mobara, Chiba, to tables across Japan, OTTO’s owner-chef Hiroyuki Kimiduka brings more than food. He creates opportunities for people to gather, talk and connect—with cooking at the heart of it all.',chef:'OWNER CHEF',
  story:[
   {n:'01',tag:'THE BEGINNING',title:'A new chapter.<br>At forty-one.',paragraphs:['Until the age of forty, Kimiduka worked as an employed chef. His hotel career included the dual roles of chef and general manager, shaping both the food and the experience around it.','At forty-one, he became independent. At OTTO, that experience now lives in two settings: the restaurant and catering. The thread connecting them is the same—cooking for the people in front of him.'],photo:'seasonal',alt:'A colourful seasonal plate prepared by OTTO'},
   {n:'02',tag:'THE CONNECTION',title:'Turn eight sideways.<br>See the possibilities.',paragraphs:['Otto means “eight” in Italian. On its side, the number becomes the symbol for infinity. Kimiduka sees himself at its crossing point, bringing people together through food.','He describes his approach as a kind of wholehearted, well-meaning involvement in people’s lives. Whether at the restaurant’s counter or a catering event, he values being close to the people he cooks for.'],photo:'gathering',alt:'Colourful small dishes prepared for a gathering'},
   {n:'03',tag:'BEYOND THE TABLE',title:'Sharing food.<br>Inspiring the next generation.',paragraphs:['Kimiduka’s work also takes him into schools. As a guest instructor, he shares the importance of eating well and thinking carefully about the information we receive about food.','He now visits elementary, junior high and high schools in Mobara, bringing work-experience sessions to students. Food becomes another way to connect—with young people discovering the world of work.'],photo:'course',alt:'Carefully arranged OTTO dishes presented on a green leaf'}
  ],
  futureTitle:'Wherever we cook,<br>people come first.',future:'Kimiduka wants to take catering beyond Chiba to more places across Japan, while continuing to run his restaurant. Serving a dish, hearing a response and taking that conversation into the next meal—this is where OTTO begins.',school:'Enquiries about school visits and work-experience sessions are welcome by phone.',
  serviceTitle:'Two ways<br>to meet at the table.',restaurantIntro:'A meal, plate by plate, at our restaurant in Mobara. By reservation only.',cateringIntro:'Corporate parties, weddings and private meals at a villa. We bring OTTO to the place you gather.',detail:'Discover more',
  restaurantHeading:'A thoughtful meal.<br>A real conversation.',restaurantText:'Seeing the people who enjoy the food. Hearing their thoughts. Our restaurant keeps the distance between chef and guest small. We welcome you, by reservation, in Mobara, Chiba.',restaurantSub:'Your next meal.<br>Thoughtfully prepared.',restaurantBody:'Lunch and dinner are by reservation only. Please tell us about your wishes when booking by phone.',priceFrom:'from',lunch:'Lunch',dinner:'Dinner',lastOrder:'Last order',photoNote:'Photographs show examples of our cuisine. Please discuss the menu when booking.',
  cateringHeading:'Your occasion.<br>Our food.',cateringText:'The food, the setting, the time you share. From corporate parties and weddings to a course meal at a villa, our catering is shaped around your occasion.',cateringSub:'Every gathering.<br>Its own menu.',cateringBody:'Every booking is individually customised. Tell us about the location, guest numbers, budget and the time you hope to create. Cooking in front of your guests is also a style we can discuss.',nation:'Across Japan',travel:'Travel expenses and other costs are discussed separately.',
  occasions:[['Corporate','Corporate gatherings','Food that invites conversation, planned around the purpose and wishes of your event.','catering-table'],['Wedding','Wedding celebrations','A table shared with the people you love, shaped around the two of you.','celebration'],['Private dining','Course meals at your villa','A chef-prepared meal in a place where you feel at home. Tell us about your preferred setting.','villa']],
  processTitle:'From a conversation<br>to your occasion.',process:[['Tell us your plans','Call to discuss the date, location, guest numbers and budget.'],['Shape the details together','We discuss the food, service style, travel expenses and other arrangements individually.'],['Gather around the table','On the day, we bring the agreed dining experience to your setting.']],
  galleryTitle:'Moments around the table.',galleryPrev:'Previous photo',galleryNext:'Next photo',galleryCaptions:['Small plates that start conversations.','Colour brought to the table.','Food prepared for people to gather.','Dessert, finished plate by plate.'],
  contactHeading:'Let’s talk<br>about your table.',contactIntro:'Restaurant reservations, catering enquiries, school visits and work-experience sessions. Please contact us by phone.',phoneLabel:'RESERVATIONS & ENQUIRIES',phone:'+81 90-6474-6012',bookingNote:'The restaurant is by reservation only. Please book by the day before your visit.',ctaTitle:'See you<br>at the next table.',address:'553-5 Mobara, Mobara-shi<br>Chiba 297-0026, Japan',addressLabel:'Address',hoursLabel:'Opening hours',closedLabel:'Closed',closed:'Irregular holidays, depending on reservations',bookingLabel:'Reservations',booking:'By phone, by the day before your visit',map:'View on Google Maps',instagram:'In the kitchen, on Instagram',instagramText:'A closer look at our food and catering.',info:'Visit & contact',back:'Back to our chef’s story',footerTag:'From food to people. From one person to another.',notfound:'This page could not be found.',notfoundText:'Please check the address or return to the homepage.',home:'Back to home'
 }
};
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function pageLink(name,lang){return name==='index'?'index.html':name+'.html';}
function photo(name,alt,prefix='',cls='',eager=false){let a=assets[name];return `<img class="${cls}" src="${prefix}assets/${name}.webp" width="${a.width}" height="${a.height}" alt="${escape(alt)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;}
function arrow(){return '<span aria-hidden="true">↗</span>';}
function link(href,label,cls='text-link',external=false){return `<a class="${cls}" href="${escape(href)}"${external?' target="_blank" rel="noopener noreferrer"':''}>${label}${arrow()}</a>`;}
function info(c){return `<dl class="info-list"><div><dt>${c.addressLabel}</dt><dd>${c.address}<br>${link(MAP,c.map,'underlined',true)}</dd></div><div><dt>${c.hoursLabel}</dt><dd>${c.lunch} 11:00–15:00 <small>(${c.lastOrder} 14:30)</small><br>${c.dinner} 18:00–22:00 <small>(${c.lastOrder} 21:30)</small></dd></div><div><dt>${c.closedLabel}</dt><dd>${c.closed}</dd></div><div><dt>${c.bookingLabel}</dt><dd>${c.booking}</dd></div></dl>`;}
function contactBlock(c,lang){return `<section class="contact-band" id="reservation"><div><span class="eyebrow">CONTACT</span><h2>${c.ctaTitle}</h2></div><div class="contact-actions"><p class="eyebrow">${c.phoneLabel}</p><a class="phone-link" href="tel:+819064746012">${c.phone}<span aria-hidden="true">↗</span></a><p class="note">${c.bookingNote}</p>${link('contact.html',c.info)}</div></section>`;}
function services(c,p){return `<section class="services section"><div class="section-heading"><span class="eyebrow">THE EXPERIENCE</span><h2>${c.serviceTitle}</h2></div><div class="service-grid"><a class="service-link" href="restaurant.html"><div class="image-wrap">${photo('vegetables','',p)}</div><div class="service-top"><h3>Restaurant</h3>${arrow()}</div><p>${c.restaurantIntro}</p></a><a class="service-link" href="catering.html"><div class="image-wrap">${photo('celebration','',p)}</div><div class="service-top"><h3>Catering</h3>${arrow()}</div><p>${c.cateringIntro}</p></a></div></section>`;}
function home(c,lang,p){return `<section class="home-hero"><div class="hero-copy"><span class="eyebrow">OTTO / OWNER CHEF’S STORY</span><h1>${c.hero}</h1><p class="lead">${c.lead}</p>${link('#story',c.read)}<span class="hero-location">${c.location}</span></div><figure class="hero-photo">${photo('signature',c.heroCaption,p,'',true)}<figcaption><span>01 — OTTO</span><span>${c.heroCaption}</span></figcaption></figure></section>
 <article id="story" class="story"><header class="story-intro section"><div><span class="eyebrow">THE PERSON BEHIND OTTO</span><h2>${c.introTitle}</h2></div><div class="intro-body"><p>${c.intro}</p><div class="chef-name"><span>${c.chef}</span><strong lang="ja">君塚 博幸</strong><span lang="en">HIROYUKI KIMIDUKA</span></div></div></header>
 <nav class="story-index" aria-label="${lang==='ja'?'記事の目次':'Story chapters'}">${c.story.map(s=>`<a href="#chapter-${s.n}"><span>${s.n}</span>${s.tag}${arrow()}</a>`).join('')}</nav>
 ${c.story.map((s,i)=>`<section class="story-chapter ${i%2?'reverse':''}" id="chapter-${s.n}"><figure class="chapter-photo reveal">${photo(s.photo,s.alt,p)}<figcaption>${s.tag} — ${s.n}</figcaption></figure><div class="chapter-text reveal"><span class="eyebrow">${s.n} / ${s.tag}</span><h2>${s.title}</h2>${s.paragraphs.map(t=>`<p>${t}</p>`).join('')}</div></section>`).join('')}
 <section class="future section"><div class="infinity" aria-hidden="true">∞</div><div><span class="eyebrow">THE STORY CONTINUES</span><h2>${c.futureTitle}</h2><p>${c.future}</p><p class="note">${c.school}</p></div></section></article>${services(c,p)}${contactBlock(c,lang)}`;}
function pageHero(c,k,p){const catering=k==='catering';const alt=c===copy.ja?(catering?'彩り豊かなOTTOのケータリング料理':'黒い皿に繊細に盛り付けられたOTTOの料理'):(catering?'Colourful dishes prepared for an OTTO catering event':'An OTTO dish carefully arranged on a black plate');return `<section class="page-hero"><div class="page-title"><span class="eyebrow">OTTO / ${k.toUpperCase()}</span><h1>${c[k+'Heading']}</h1><p class="lead">${c[k+'Text']}</p></div><figure>${photo(catering?'gathering':'signature',alt,p,'',true)}<figcaption>${catering?'CATERING ACROSS JAPAN':'RESTAURANT IN MOBARA, CHIBA'}</figcaption></figure></section>`;}
function restaurant(c,lang,p){return `${pageHero(c,'restaurant',p)}<section class="restaurant-menu section"><div class="section-heading"><span class="eyebrow">BY RESERVATION ONLY</span><h2>${c.restaurantSub}</h2><p>${c.restaurantBody}</p></div><div class="course-prices">${[['Lunch',c.lunch,'2,800','11:00–15:00','14:30'],['Dinner',c.dinner,'8,000','18:00–22:00','21:30']].map(([en,jp,price,hours,last])=>`<div class="price-row"><div><h3>${en}</h3>${lang==='ja'?'<span>'+jp+'</span>':''}</div><p class="price">${lang==='en'?'<small>from</small> ':''}¥${price}${lang==='ja'?'<small>〜</small>':''}</p><p>${hours}<br><small>${c.lastOrder} ${last}</small></p></div>`).join('')}<p class="note">${c.bookingNote}</p>${link('tel:+819064746012',c.phoneLabel)}</div></section><section class="plate-gallery"><figure>${photo('course',lang==='ja'?'丁寧に盛り付けた小さな料理':'Carefully arranged small dishes',p)}</figure><figure>${photo('fish',lang==='ja'?'ソースを添えた料理':'A dish finished with sauce',p)}</figure><figure>${photo('soup',lang==='ja'?'器に盛り付けた季節の料理':'A seasonal dish in a ceramic bowl',p)}</figure></section><p class="gallery-note note">${c.photoNote}</p><section class="visit-section section"><div><span class="eyebrow">FIND US</span><h2>Mobara,<br>Chiba.</h2><p>${c.address}</p>${link(MAP,c.map,'text-link',true)}</div>${info(c)}</section>${contactBlock(c,lang)}`;}
function catering(c,lang,p){return `${pageHero(c,'catering',p)}<section class="catering-intro section"><div><span class="eyebrow">BESPOKE CATERING</span><h2>${c.cateringSub}</h2></div><div><p>${c.cateringBody}</p><div class="nation"><strong>${c.nation}</strong><span>${c.travel}</span></div></div></section><section class="occasions">${c.occasions.map(([label,title,text,name],i)=>`<article class="occasion"><div class="image-wrap">${photo(name,title,p)}</div><div><span class="eyebrow">0${i+1} / ${label.toUpperCase()}</span><h2>${title}</h2><p>${text}</p></div></article>`).join('')}</section><section class="catering-gallery section"><div class="gallery-heading"><div><span class="eyebrow">A FEW MOMENTS</span><h2>${c.galleryTitle}</h2></div><div class="gallery-controls"><button type="button" data-prev aria-label="${c.galleryPrev}">←</button><span data-count>01 / 04</span><button type="button" data-next aria-label="${c.galleryNext}">→</button></div></div><div class="gallery" aria-roledescription="${lang==='ja'?'スライドショー':'carousel'}" aria-label="${c.galleryTitle}">${['small-plates','gathering','catering-table','dessert'].map((name,i)=>`<figure class="gallery-slide" ${i?'hidden':''}>${photo(name,c.galleryCaptions[i],p)}<figcaption>${c.galleryCaptions[i]}</figcaption></figure>`).join('')}</div><p class="sr-only" data-gallery-status aria-live="polite"></p></section><section class="process section"><div class="section-heading"><span class="eyebrow">HOW IT WORKS</span><h2>${c.processTitle}</h2></div><ol>${c.process.map(([title,text],i)=>`<li><span>0${i+1}</span><h3>${title}</h3><p>${text}</p></li>`).join('')}</ol></section>${contactBlock(c,lang)}`;}
function contact(c,lang,p){return `<section class="contact-page section"><span class="eyebrow">OTTO / VISIT & CONTACT</span><h1>${c.contactHeading}</h1><div class="contact-layout"><div><p class="lead">${c.contactIntro}</p><div class="phone-box"><p class="eyebrow">${c.phoneLabel}</p><a class="phone-link" href="tel:+819064746012">${c.phone}${arrow()}</a><p class="note">${c.bookingNote}</p></div><div class="social-block"><h2>${c.instagram}</h2><p>${c.instagramText}</p>${link(INSTAGRAM,'@catering_restaurant_otto','text-link',true)}</div></div><div>${info(c)}<div class="address-mark"><span>OTTO</span><p>MOBARA, CHIBA<br>〒297-0026</p></div></div></div></section><div class="contact-photo">${photo('vegetables',lang==='ja'?'OTTOの彩り豊かな料理':'Colourful cuisine at OTTO',p)}</div>`;}
function shell(lang,k,body){const c=copy[lang],p=lang==='en'?'../':'',idx=names.indexOf(k),other=(lang==='en'?'../':'en/')+k+'.html';return `<!doctype html>
<html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${c.title[idx]||'OTTO | 404'}</title><meta name="description" content="${escape(c.desc)}"><meta name="theme-color" content="#fbfaf7"><meta property="og:title" content="${c.title[idx]||'OTTO'}"><meta property="og:description" content="${escape(c.desc)}"><meta property="og:type" content="website"><link rel="icon" href="${p}assets/favicon.svg" type="image/svg+xml"><link rel="alternate" hreflang="${lang==='ja'?'en':'ja'}" href="${other}"><link rel="stylesheet" href="${p}assets/style.css"><script src="${p}assets/site.js" defer></script></head><body data-page="${k}"><a class="skip-link" href="#main">${c.skip}</a><div class="reading-progress" aria-hidden="true"></div><header class="site-header"><a class="wordmark" href="index.html" aria-label="OTTO ${c.home}">OTTO<span>CATERING & RESTAURANT</span></a><nav class="desktop-nav" aria-label="${c.menu}">${names.map((n,i)=>`<a href="${pageLink(n,lang)}"${n===k?' aria-current="page"':''}>${c.nav[i]}</a>`).join('')}</nav><div class="header-end"><nav class="language-nav" aria-label="${c.lang}"><a href="${lang==='en'?'../':''}${k}.html" lang="ja"${lang==='ja'?' aria-current="true"':''}>JP</a><span>/</span><a href="${lang==='ja'?'en/':''}${k}.html" lang="en"${lang==='en'?' aria-current="true"':''}>EN</a></nav><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-navigation"><span class="menu-label">${c.menu}</span><span class="menu-icon" aria-hidden="true"></span></button></div><nav class="mobile-nav" id="mobile-navigation" aria-label="${c.menu}" hidden>${names.map((n,i)=>`<a href="${pageLink(n,lang)}"${n===k?' aria-current="page"':''}><span>0${i+1}</span>${c.nav[i]}${arrow()}</a>`).join('')}<a href="tel:+819064746012">${c.phone}${arrow()}</a></nav></header><main id="main">${body}</main><footer class="site-footer"><div class="footer-brand"><a class="wordmark" href="index.html">OTTO<span>CATERING & RESTAURANT</span></a><p>${c.footerTag}</p></div><div class="footer-links">${names.map((n,i)=>`<a href="${n}.html">${c.nav[i]}</a>`).join('')}<a href="${INSTAGRAM}" target="_blank" rel="noopener noreferrer">Instagram ↗</a></div><div class="footer-bottom"><span>© OTTO</span><span>MOBARA, CHIBA — JAPAN</span><a href="#main" aria-label="${lang==='ja'?'ページの先頭へ':'Back to top'}">↑</a></div></footer></body></html>`;}
for(const lang of languages){const p=lang==='en'?'../':'';await mkdir(path.join(out,lang==='en'?'en':''),{recursive:true});for(const k of names){const render={index:home,restaurant,catering,contact}[k];await writeFile(path.join(out,lang==='en'?'en':'',k+'.html'),shell(lang,k,render(copy[lang],lang,p)));}}
const c=copy.ja;let notfound=shell('ja','index',`<section class="not-found section"><span class="eyebrow">404 / OTTO</span><h1>${c.notfound}</h1><p>${c.notfoundText}</p>${link('/',c.home)}</section>`).replaceAll('href="assets/','href="/assets/').replaceAll('src="assets/','src="/assets/').replace(/href="(index|restaurant|catering|contact)\.html/g,'href="/$1.html').replace('href="en/index.html','href="/en/index.html').replace('<title>'+c.title[0]+'</title>','<title>ページが見つかりません｜OTTO</title><meta name="robots" content="noindex">');
await writeFile(path.join(out,'404.html'),notfound);
console.log('Built 8 bilingual pages and a 404 page for Cloudflare Pages.');
